### PR TITLE
Add support for YAML config

### PR DESCRIPTION
**Pull request by RaeesBhatti**
Fixes: https://github.com/netlify/cli/issues/565

### CODE REVIEW

**Comment by DavidWells** [comment]
We for sure need `yml` support nice work.

I think we need to consolidate and use `@netlify/config` everywhere so variables etc resolve correctly https://github.com/netlify/build/tree/master/packages/config

This is also true for in the CLI https://github.com/netlify/cli/blob/7ddd543fa131c2531c5861f8bdc049cabbe6e6f3/src/utils/command.js#L36

**Comment by raeesbhatti** [comment]
Should we implement using `@netlify/config` here now since we already implemented that in the CLI. Not sure how that affects this PR!

**Comment by DavidWells** [comment]
Yeah for sure. The config parsing is happening 2 places right now 

1. inside cli command https://github.com/netlify/cli/blob/master/src/utils/command.js#L39-L40
2. inside netlify/build when `netlify build` cli command is run
3. and this lib

The yaml/json/toml/etc is already parsed when this lib is used and the resolved object is `this.netlify.config` in the CLI

Perhaps this lib can use that already resolved object instead of trying to parse things again?

**Comment by DavidWells** [comment]
Is this library used anywhere else other than the CLI?

**Comment by sw-yx** [comment]
that readme was old. raees unmoved it. bad call to merge it in but we didnt forsee netlify build at the time

**Pull request merged**
